name: loop-test-build

on: push

jobs:

  x86:
    name: x86
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: ipxe/ipxe
          path: .
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind \
                           gcc-arm-none-eabi gcc-aarch64-linux-gnu
      - name: Build (BIOS)
        run: |
          make -j 4 -C src
      - name: Build ARM32
        run: |
          make -j 4 -C src CROSS=arm-none-eabi- \
               bin-arm32-efi/intel.efi \
               bin-arm32-efi/intel.usb \
               bin-arm32-efi/intel.iso
      - name: Build ARM64
        run: |
          make -j 4 -C src CROSS=aarch64-linux-gnu- \
               bin-arm64-efi/ipxe.efi \
               bin-arm64-efi/ipxe.usb \
               bin-arm64-efi/ipxe.iso
      - name: Build ISO
        run: |
          cd src && ./util/genfsimg -o ipxe-all-arch.iso -s menu.ipxe \
          bin-i386-efi/ipxe.efi \
          bin-x86_64-efi/ipxe.efi \
          bin-arm32-efi/ipxe.efi \
          bin-arm64-efi/ipxe.efi \
          bin/ipxe.lkrn
      - name: Build (Everything)
        run: |
          make -j 4 -C src everything
      - name: Test
        run: |
          valgrind ./src/bin-i386-linux/tests.linux
          valgrind ./src/bin-x86_64-linux/tests.linux
