name: loop-test-build

on: push

jobs:

  x86:
    name: x86-loop-test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: ipxe/ipxe
          path: .
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind \
                           p7zip-full genisoimage mtools isolinux syslinux syslinux-efi syslinux-utils xorriso
      - name: install ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}
      - name: Build (BIOS)
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j 4 -C src
      - name: Install packages arm gcc
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux genisoimage xorriso mtools \
                           gcc-arm-none-eabi \
                           gcc-aarch64-linux-gnu \
                           g++-9-aarch64-linux-gnu
      - name: Build ARM32
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j 4 -C src CROSS=arm-none-eabi- \
               bin-arm32-efi/intel.efi \
               bin-arm32-efi/intel.usb \
               bin-arm32-efi/intel.iso
      - name: Build ARM64
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j 4 -C src CROSS=aarch64-linux-gnu- \
               bin-arm64-efi/ipxe.efi \
               bin-arm64-efi/ipxe.usb \
               bin-arm64-efi/ipxe.iso

      - name: Install for ISO build
        run: |
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           p7zip-full genisoimage mtools isolinux syslinux syslinux-efi syslinux-utils xorriso
      - name: Build ISO
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          find . \( -name "*.lkrn" -or -name "*.efi" -or -name "*.iso" \) \( ! -name "Makefile*" \) -print
          cd src && ./util/genfsimg -o ipxe-all-arch.iso -s menu.ipxe \
          bin-i386-efi/ipxe.efi \
          bin-x86_64-efi/ipxe.efi \
          bin-arm32-efi/ipxe.efi \
          bin-arm64-efi/ipxe.efi \
          bin/ipxe.lkrn || \
          ./util/genfsimg -o ipxe-any.iso bin-*-efi/ipxe.efi bin/ipxe.lkrn
      - name: list ISO
        run: |
          find . \( -name "*.lkrn" -or -name "*.efi" -or -name "*.iso" \) \( ! -name "Makefile*" \) -print
          isoinfo -d -i src/*.iso
          isoinfo -l -i src/*.iso
          7z l src/my.iso
      - name: Build (Everything)
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j 4 -C src everything
      - name: Build ISO (Everything)
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          find . -name ipxe.lkrn -or -name ipxe.efi -print
          cd src && ./util/genfsimg -o ipxe-all-arch.iso -s menu.ipxe \
          bin-i386-efi/ipxe.efi \
          bin-x86_64-efi/ipxe.efi \
          bin-arm32-efi/ipxe.efi \
          bin-arm64-efi/ipxe.efi \
          bin/ipxe.lkrn || \
          ./util/genfsimg -o ipxe-glob.iso bin-*-efi/ipxe.efi bin/ipxe.lkrn
      - name: list ISO (Everything)
        continue-on-error: true
        run: |
          find . \( -name "*.lkrn" -or -name "*.lkr" -or -name "*.efi" -or -name "*.iso" \) \( ! -name "Makefile*" \) -print
          isoinfo -d -i src/*.iso
          isoinfo -l -i src/*.iso
          7z l src/my.iso
      - name: Test
        run: |
          valgrind ./src/bin-i386-linux/tests.linux
          valgrind ./src/bin-x86_64-linux/tests.linux
###
      - name: ssh
        if: ${{ false() }}
        continue-on-error: false
        #if: ${{ failure() }}
        #if: ${{ true() }}
        #continue-on-error: true
        uses: ryanchapman/gha-ssh@v1
      # after the container starts tmate in the background, it will
      # sleep for 24 hours, so it's important that you set a timeout here
      # so you doif: ${{ failure() }}n't run up your GitHub Actions bill
        timeout-minutes: 10
        with:
        # authorized_github_users: required
        # List of GitHub users who are allowed to ssh into container.
        # On gha-ssh container start, it downloads the ssh public key(s) for each
        # user from GitHub and places it in ~/authorized_keys
        # tmate is started with `-a ~/authorized_keys` to only allow access
        # to users with possession of the corresponding private ssh keys.
          #authorized_github_users: 'johndoe,janedoe'
          authorized_github_users: 'woa7'
        # debug: optional
        # defaults to `false` if not set here
        # if debug is set, then tmate is started with `-vvv -F`
          debug: true
      - name: foo run
        run: |
          echo foo
###

